### ISSUE TITLE
Smaller Stepper Touch

### ISSUE THREAD

**Issue by udongeex** [DanielMartinus/Stepper-Touch#38]
I need to set the stepper touch with below size for a full display
android:layout_width="130dp"
android:layout_height="50dp
Is there a way I can make it smaller ? Thanks a lot

**Comment by artprasetya** [comment]
i have same problem

**Comment by DanielMartinus** [comment]
I've seen the issue, thanks for reporting. Currently there is no way of making it smaller. In order to make this work I will have to make some changes. I can't say when I will have a fix for it yet but It's on my list.

**Comment by DanielMartinus** [comment]
As you can see in the image below it's now resizable to a smaller size than 130dp by 50dp. When the linked pull request in this issue is merged I will release a new version with the fix.

<img src="https://user-images.githubusercontent.com/1636897/54871322-7d1bc480-4db2-11e9-9324-97c775971803.png" width=300/>

In order to get the same look as the top stepper I also had to configure the margins and the size of the text. 

In your **layout.xml** you can use for example 80dp by 32dp or anything else.

```xml
<nl.dionsegijn.steppertouch.StepperTouch
                android:id="@+id/stepperTouch"
                android:layout_width="80dp"
                android:layout_height="32dp"
                android:layout_margin="40dp"
                android:clipChildren="true"
                android:orientation="horizontal"/>
```

But do note, you'll have to change the margins and text size by overriding it in the **dimens.xml** of your app, for example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="stepper_side_control_margin_start">8dp</dimen>
    <dimen name="stepper_side_control_margin_end">8dp</dimen>
    <dimen name="stepper_side_control_text_size">18sp</dimen>
</resources>
```

**Comment by DanielMartinus** [comment]
Update 1.0.1 should now be available:

```gradle
dependencies {
    implementation 'com.github.DanielMartinus:Stepper-Touch:1.0.1'
}
```
