### ISSUE TITLE
Make (-) and (+) texts clickable

### ISSUE THREAD

**Issue by olivierperez** [DanielMartinus/Stepper-Touch#4]
Can you convert - and + texts to buttons that remove or add 1 to the value ?

It would be great if you animate the value when the buttons are clicked.

**Comment by DanielMartinus** [comment]
I've gotten this more often as Feedback. First I wasn't really planning to do so because it was intentionally not added. I followed the guidelines of the official designer here: https://material.uplabs.com/posts/stepper-touch-interface

But having this more as feedback it would indeed seem as a logical decision to implement. Would you expect the middle button the so called `StepperCounter` to animate left or right when clicking either - or +?

**Comment by olivierperez** [comment]
Thanks!

Yes if you can animate the `StepperCounter` it's cool. By the way, it's not a "**must have**" but a "**nice to have**" 😄

**Comment by DanielMartinus** [comment]
See implementation in linked pull request. Feel free to check out the branch, play with it and provide me with any feedback.
